language: node_js
node_js:
  - "6.9"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
git:
  depth: 3
  
script:
  - ng build

deploy:
  name : Kafil Nasdami
  email: kafil.nasdami@gmail.com
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  fqdn: www.kafil.xyz
  on:
    branch: master