language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href "https://kafiil.github.io/ng-profile/" ngh

after_success:
  - ngh